### PR TITLE
Frontend/Fix pw input validation messages

### LINKED ISSUE #410: Password update validation bug
Path: `/Account`

The validation messages are all 'green', but the box is red. It's not clear why.

To reproduce,

1. Navigate to "Account" page
2. Enter current password (in my case, Josh12345678)
3. Enter new password (in my case, Josh123456789)
4. All errors are green, but the textbox is red and I cannot submit.

Similarly, if I type a new password as "12345678901", all of the validation items are green, even though there is most definitely not a special, lowercase, or uppercase character in the input box.

image

_Originally posted by @jlkravitz in https://github.com/csg-org/CompactConnect/pull/401#discussion_r1890689105_

### PR DESCRIPTION
**Pull request by jsandoval81**
### Requirements List
- _None_

### Description List
- Move message augmentation to after message evaluation
- Update frontend to match latest backend pw requirements (length only)
- Add tests

### Testing List
- `yarn test:unit:all` should run without errors or warnings
- `yarn serve` should run without errors or warnings
- `yarn build` should run without errors or warnings
- Code review
- Fill out the change-password section of the account page to ensure correct validation behavior
    - No need to actually submit the change

Closes #410

### CODE REVIEW

File: webroot/src/components/ChangePassword/ChangePassword.ts [hunk 1]
```diff
@@ -100,10 +100,6 @@ class ChangePassword extends mixins(MixinForm) {
                 validation: joiPassword
                     .string()
                     .min(12)
-                    .minOfSpecialCharacters(1)
-                    .minOfLowercase(1)
-                    .minOfUppercase(1)
-                    .minOfNumeric(1)
                     .doesNotInclude([
                         this.user.email,
```
Comment (ChiefStief) [inline webroot/src/components/ChangePassword/ChangePassword.ts:104]: This ticket as described looks good. I noticed that the common string validator is case sensitive, so when I put "dana" in as part of my password it lets me. Not sure if you want to address this here or at all.

Comment (ChiefStief) [reply webroot/src/components/ChangePassword/ChangePassword.ts:104]: Makes sense, on the MVP point. All that works for me.

**Review by ChiefStief — APPROVED** [review]

**Comment by jsandoval81** [comment]
@jlkravitz This is ready for your review.

File: webroot/src/components/ChangePassword/ChangePassword.ts [hunk 2]
```diff
@@ -100,15 +100,8 @@ class ChangePassword extends mixins(MixinForm) {
                 validation: joiPassword
                     .string()
                     .min(12)
-                    .minOfSpecialCharacters(1)
```
Comment (jlkravitz) [inline webroot/src/components/ChangePassword/ChangePassword.ts:103]: Why are we removing these requirements, yet still testing them below?

(I know we had briefly discussed updated NIST guidelines several weeks ago - related? Generally, I'm keen to remove complexity requirements and keep only length requirements, as I believe NIST recommends.)

Comment (jsandoval81) [reply webroot/src/components/ChangePassword/ChangePassword.ts:103]: The tests are just for the generic functionality of the low-level InputPassword component, so we know we can use them later if needed.

You're correct that the app implementation in this ChangePassword component has also been updated to use the latest NIST recommendation. That was the decision on the last standup call - I went ahead and added that comment to the ticket just now.

Comment (jlkravitz) [reply webroot/src/components/ChangePassword/ChangePassword.ts:103]: Got it- thank you for the context!

**Review by jlkravitz — APPROVED** [review]
@isabeleliassen This is good to go.
